### ISSUE TITLE
Party API - multiple kind attribute

### ISSUE THREAD

**Issue by cdubalaru** [asseco-see/api-descriptions#21]
There are multiple kind attributes of parties:
1. kind - For a list of possible values see party-kinds enumeration.
2. kind - Kind of identification number
3. kind - Classifies customers according to taxonomy defined by bank.

**Comment by amilos** [comment]
This is by design. Each of those kinds explains different things. 
- Enumeration `party-kinds` defines whether party is an `organization` or `individual`
- Enumeration `identification-kinds` defines what kind of external id number is supplied
- Classification `customer-taxonomy` defines internal bank classification of different kinds of customers that bank deals with. This is usually combination of legal status, legal entity kind, residential status and is typically used to distinguish between different organizational customers.
