### ISSUE TITLE
Party API lacks updating customer data method/option .

### ISSUE THREAD

**Issue by rkrulj** [asseco-see/api-descriptions#27]
Some implementations of the online registration process require draft saving option and later completing of the application. Currently **/parties/individuals** route has only **POST** verb option to create a new application, but doesn't provide **PUT** or **PATCH** option to update existing one.

**Comment by amilos** [comment]
Party API is **not responsible** for online registration process that is specific to some bank. It offers standardized services to register clients at a point in process where enough data is available for registration.
Generic updating of any customer information is **not responsibility** of Party API as this would circumvent any specific logic that needs to guard party data when some concrete changes are reported such as change of address.   b
Instead of generic update method suggest concrete change of party information for some recognized business event - change of id document, change of address, change of name.

**Comment by cdubalaru** [comment]
Is not so clear how to treat this. Can you give a complete and clear example. The comment is to generic and abstract.

**Comment by amilos** [comment]
I gave few examples above so lets take one of them and describe it in mode details. 
> Customer has changed his national id card and is reporting this change to bank. Bank clerk examines the changed id document and enters the details of new document in branch application. 

To complete this task application needs a new API method to **register identification document** so we introduce it at the following endpoint: POST /parties/party-number/id-documents with payload that contains details of the document.

This is handling concrete business problem with appropriate API method at *business problem level* instead of having API at the *data storage level*.
